import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  scopesSidebar: [
    'scopes/intro',
    'scopes/phase1',
    'scopes/phase2',
  ],
  journalSidebar: [{type: 'autogenerated', dirName: 'journal'}],
};

export default sidebars;
